pincode_db = {
    "110001": {
        "pincode": "110001",
        "city": "New Delhi",
        "state": "Delhi",
        "district": "New Delhi",
    },
    "201301": {
        "pincode": "201301",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "district": "Gautam Buddha Nagar",
    },
    "201310": {
        "pincode": "201310",
        "city": "Greater Noida",
        "state": "Uttar Pradesh",
        "district": "Gautam Buddha Nagar",
    },
    "122001": {
        "pincode": "122001",
        "city": "Gurugram",
        "state": "Haryana",
        "district": "Gurugram",
    },
    "400001": {
        "pincode": "400001",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai",
    },
    "411001": {
        "pincode": "411001",
        "city": "Pune",
        "state": "Maharashtra",
        "district": "Pune",
    },
    "440001": {
        "pincode": "440001",
        "city": "Nagpur",
        "state": "Maharashtra",
        "district": "Nagpur",
    },
    "560001": {
        "pincode": "560001",
        "city": "Bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
    },
    "560034": {
        "pincode": "560034",
        "city": "Bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
    },
    "600001": {
        "pincode": "600001",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "district": "Chennai",
    },
    "600017": {
        "pincode": "600017",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "district": "Chennai",
    },
    "500001": {
        "pincode": "500001",
        "city": "Hyderabad",
        "state": "Telangana",
        "district": "Hyderabad",
    },
    "500081": {
        "pincode": "500081",
        "city": "Hyderabad",
        "state": "Telangana",
        "district": "Ranga Reddy",
    },
    "700001": {
        "pincode": "700001",
        "city": "Kolkata",
        "state": "West Bengal",
        "district": "Kolkata",
    },
    "700156": {
        "pincode": "700156",
        "city": "Kolkata",
        "state": "West Bengal",
        "district": "North 24 Parganas",
    },
    "380001": {
        "pincode": "380001",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "district": "Ahmedabad",
    },
    "395001": {
        "pincode": "395001",
        "city": "Surat",
        "state": "Gujarat",
        "district": "Surat",
    },
    "302001": {
        "pincode": "302001",
        "city": "Jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
    },
    "313001": {
        "pincode": "313001",
        "city": "Udaipur",
        "state": "Rajasthan",
        "district": "Udaipur",
    },
    "226001": {
        "pincode": "226001",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
    },
    "208001": {
        "pincode": "208001",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "district": "Kanpur Nagar",
    },
    "221001": {
        "pincode": "221001",
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
    },
    "800001": {
        "pincode": "800001",
        "city": "Patna",
        "state": "Bihar",
        "district": "Patna",
    },
    "834001": {
        "pincode": "834001",
        "city": "Ranchi",
        "state": "Jharkhand",
        "district": "Ranchi",
    },
    "751001": {
        "pincode": "751001",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "district": "Khordha",
    },
    "492001": {
        "pincode": "492001",
        "city": "Raipur",
        "state": "Chhattisgarh",
        "district": "Raipur",
    },
    "462001": {
        "pincode": "462001",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
    },
    "452001": {
        "pincode": "452001",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "district": "Indore",
    },
    "682001": {
        "pincode": "682001",
        "city": "Kochi",
        "state": "Kerala",
        "district": "Ernakulam",
    },
    "695001": {
        "pincode": "695001",
        "city": "Thiruvananthapuram",
        "state": "Kerala",
        "district": "Thiruvananthapuram",
    },
    "530001": {
        "pincode": "530001",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "district": "Visakhapatnam",
    },
    "522001": {
        "pincode": "522001",
        "city": "Guntur",
        "state": "Andhra Pradesh",
        "district": "Guntur",
    },
    "781001": {
        "pincode": "781001",
        "city": "Guwahati",
        "state": "Assam",
        "district": "Kamrup Metropolitan",
    },
    "160001": {
        "pincode": "160001",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "district": "Chandigarh",
    },
    "141001": {
        "pincode": "141001",
        "city": "Ludhiana",
        "state": "Punjab",
        "district": "Ludhiana",
    },
    "248001": {
        "pincode": "248001",
        "city": "Dehradun",
        "state": "Uttarakhand",
        "district": "Dehradun",
    },
    "171001": {
        "pincode": "171001",
        "city": "Shimla",
        "state": "Himachal Pradesh",
        "district": "Shimla",
    },
    "403001": {
        "pincode": "403001",
        "city": "Panaji",
        "state": "Goa",
        "district": "North Goa",
    },
    "190001": {
        "pincode": "190001",
        "city": "Srinagar",
        "state": "Jammu and Kashmir",
        "district": "Srinagar",
    },
    "194101": {
        "pincode": "194101",
        "city": "Leh",
        "state": "Ladakh",
        "district": "Leh",
    },
}